################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
EXECUTABLES := 
OBJS := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Modules/DHCPClient \
Core/Modules/altcp_tls \
Core/Modules/sntp_client \
Core/Src \
Core/Startup \
Drivers/STM32F7xx_HAL_Driver/Src/Legacy \
Drivers/STM32F7xx_HAL_Driver/Src \
GUI/assets \
GUI \
Middlewares/LwIP/src/api \
Middlewares/LwIP/src/core \
Middlewares/LwIP/src/core/ipv4 \
Middlewares/LwIP/src/netif \
Middlewares/LwIP/src/netif/ppp \
Middlewares/LwIP/src/netif/ppp/polarssl \
Middlewares/LwIP/system/OS \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 \
Middlewares/Third_Party/FreeRTOS/Source \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang \
Middlewares/mbedTLS/library \
Utilities/Components/adv7533 \
Utilities/Components/exc7200 \
Utilities/Components/ft5336 \
Utilities/Components/ft6x06 \
Utilities/Components/mfxstm32l152 \
Utilities/Components/otm8009a \
Utilities/Components/ov9655 \
Utilities/Components/s5k5cag \
Utilities/Components/st7735 \
Utilities/Components/st7789h2 \
Utilities/Components/stmpe811 \
Utilities/Components/ts3510 \
Utilities/Components/wm8994 \
Utilities/Log \
Utilities/STM32F769I-Discovery \
hal_stm_lvgl/tft \
hal_stm_lvgl/touchpad \
lvgl/examples/anim \
lvgl/examples/assets \
lvgl/examples/event \
lvgl/examples/get_started \
lvgl/examples/layouts/flex \
lvgl/examples/layouts/grid \
lvgl/examples/porting \
lvgl/examples/scroll \
lvgl/examples/styles \
lvgl/examples/widgets/animimg \
lvgl/examples/widgets/arc \
lvgl/examples/widgets/bar \
lvgl/examples/widgets/btn \
lvgl/examples/widgets/btnmatrix \
lvgl/examples/widgets/calendar \
lvgl/examples/widgets/canvas \
lvgl/examples/widgets/chart \
lvgl/examples/widgets/checkbox \
lvgl/examples/widgets/colorwheel \
lvgl/examples/widgets/dropdown \
lvgl/examples/widgets/img \
lvgl/examples/widgets/imgbtn \
lvgl/examples/widgets/keyboard \
lvgl/examples/widgets/label \
lvgl/examples/widgets/led \
lvgl/examples/widgets/line \
lvgl/examples/widgets/list \
lvgl/examples/widgets/meter \
lvgl/examples/widgets/msgbox \
lvgl/examples/widgets/obj \
lvgl/examples/widgets/roller \
lvgl/examples/widgets/slider \
lvgl/examples/widgets/span \
lvgl/examples/widgets/spinbox \
lvgl/examples/widgets/spinner \
lvgl/examples/widgets/switch \
lvgl/examples/widgets/table \
lvgl/examples/widgets/tabview \
lvgl/examples/widgets/textarea \
lvgl/examples/widgets/tileview \
lvgl/examples/widgets/win \
lvgl/src/core \
lvgl/src/draw \
lvgl/src/extra/layouts/flex \
lvgl/src/extra/layouts/grid \
lvgl/src/extra \
lvgl/src/extra/themes/basic \
lvgl/src/extra/themes/default \
lvgl/src/extra/themes/mono \
lvgl/src/extra/widgets/animimg \
lvgl/src/extra/widgets/calendar \
lvgl/src/extra/widgets/chart \
lvgl/src/extra/widgets/colorwheel \
lvgl/src/extra/widgets/imgbtn \
lvgl/src/extra/widgets/keyboard \
lvgl/src/extra/widgets/led \
lvgl/src/extra/widgets/list \
lvgl/src/extra/widgets/meter \
lvgl/src/extra/widgets/msgbox \
lvgl/src/extra/widgets/span \
lvgl/src/extra/widgets/spinbox \
lvgl/src/extra/widgets/spinner \
lvgl/src/extra/widgets/tabview \
lvgl/src/extra/widgets/tileview \
lvgl/src/extra/widgets/win \
lvgl/src/font \
lvgl/src/gpu \
lvgl/src/hal \
lvgl/src/misc \
lvgl/src/widgets \
lvgl/tests \
lvgl/tests/lv_test_core \
lvgl/tests/lv_test_fonts \
lvgl/tests/lv_test_widgets \

